version: '3'

services:
  web:
    restart: always
    build: ./web
    container_name: web
    # expose:
    #   - "8000"
    ports:
      - "8000:8000"
    links:
      - pgdb:pgdb
    volumes:
      - web-static:/usr/src/app/static
    env_file: .env
    # command: /usr/local/bin/gunicorn amogusus_test.wsgi:application -w 2 -b :8000
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - web-static:/usr/src/app/static

    # nginx:
    #   restart: always
    #   build: ./nginx/
    #   ports:
    #     - "80:80"
    #   volumes:
    #     - web-static:/www/static
    #   links:
    #     - web:web

  pgdb:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdb_persistent:/var/lib/postgresql/data/

volumes:
  web-static:
  pgdb_persistent:
