# Generated by Django 4.0.1 on 2022-01-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('case_hash', models.DecimalField(decimal_places=0, default=14911, max_digits=10000)),
            ],
        ),
    ]
